name: Deploy
on:
  workflow_call:
    inputs:
      deploy_ref:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ input.deploy_ref }}
      - name: build
        run: echo "build project ${{ input.deploy_ref }}"
      - name: deploy
        run: echo "deploy project ${{ secrets.MY_DEPLOY_KEY }}"
