name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy_ref:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.deploy_ref }}
      - name: build
        run: echo "build project ${{ inputs.deploy_ref }}"
      - name: deploy
        run: echo "deploy project ${{ secrets.MY_DEPLOY_KEY }}"
