name: Build CI Workflow Environment
on:
  push:
    paths:
      - .github/env/training/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .github/env/training
          file: ./Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:environment-training'
