
name: test example cml pr create cmd

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Create Pull Request
        run: |
          echo "make an edit" >> cml.log
          echo "body of pr" >> ./pr-body.md
          echo "body of pr" >> ./pr-body.md

          cml pr create \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --message="message" \
            --title="title" \
            --body="$(cat ./pr-body.md)" .