name: cml create comment image upload
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: add images
        run: |
          for file in assets/*; do
            echo $file
          done
