name: cml pr
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #cml ci
          cml pr "."

          echo "stuff" > reports.md

