name: cml create comment image upload
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: add images
        run: |
          touch report.md
          echo "# test comment" > report.md
          for file in assets/*; do
            echo "### test image" >> report.md
            echo "![](./${file})" >> report.md
          done
          cat ./report.md
