---
name: Understanding jobs.<job_id>.container
on: workflow_dispatch
jobs:
  test_cml-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l
      - run: uname -a
      - run: python --version
  test_container:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l
      - run: uname -a
      - run: python --version
  test_ubunut-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l
      - run: uname -a
      - run: python --version
