name: test dvc exp
on:
  workflow_dispatch:
  push:
jobs:
  neg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: iterative/setup-dvc@v1
      - run: |
          echo "stages:" >> dvc.yaml
          echo "  train:" >> dvc.yaml
          echo "    cmd: date" >> dvc.yaml
      - run: |
          dvc init
          dvc exp run
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo "stages:" >> dvc.yaml
          echo "  train:" >> dvc.yaml
          echo "    cmd: date" >> dvc.yaml
      - run: |
          dvc init
          dvc exp run