name: test dvc exp
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<-END
            stages:
              train:
                cmd: date
          END > dvc.yaml
      - run: |
          dvc init
          dvc exp run