on:
  # https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [trigger-test]

jobs:
  some_job:
    environment: ${{ github.event.client_payload.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
      - run: |
          echo "test environment secret"
          echo "${{ secrets.ONLY_ON_REPODIS  }}"
          echo "${{ secrets.ONLY_ON_REPODIS  }}" | md5sum
      - uses: ./.github/workflows/workflow_call.yml@main
        with:
          some_config_option: ${{ github.event.client_payload.tag }}
          some_token: ${{ secrets.ONLY_ON_REPODIS }}
