---
name: Github action pip install fail
on: workflow_dispatch
jobs:
  test_container:
    runs-on: ubuntu-latest
    container:
      image: python:buster
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l
      - run: uname -a
      - run: python --version
      - run: |
          pip config debug
          pip config list
          pip debug
      - run: pip install tensorflow==2.5.0
