name: print refs
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ github.event.pull_request.head.sha }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.sha }}"
      - run: echo "${{ github.ref }}"
