name: runner gitconfig?
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DACBD_PAT }}
      - run: |
          git config --list
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git clone https://github.com/dacbd/err.git test1
          #git clone https://github.com/dacbd/err-private.git test0
          ls -hal
      - name: setup gh
        run: |
          echo "${{ secrets.DACBD_PAT }}" | gh auth login --hostname github.com --with-token
          gh auth setup-git
      - name: spin 1
        run:
          sleep 7200
      - name: spin 2
        run:
          sleep 7200
      - name: spin 3
        run:
          sleep 7200
      - name: spin 4
        run:
          sleep 7200
      - name: spin 5
        run:
          sleep 7200
      - name: spin 6
        run:
          sleep 7200
      - name: spin 7
        run:
          sleep 7200
      - name: spin 8
        run:
          sleep 7200
      - name: spin 9
        run:
          sleep 7200
      - name: spin 10
        run:
          sleep 7200
      - name: spin 11
        run:
          sleep 7200
      - name: spin 12
        run:
          sleep 7200
      - name: spin 13
        run:
          sleep 7200
      - run: |
          git config --list
          git config --unset-all http.https://github.com/.extraheader
          git config --list
          git clone https://github.com/dacbd/err-private.git test2
          ls -hal

